### ISSUE TITLE
Error: Variable "$_data" got invalid value 

### ISSUE THREAD

**Issue by gHashTag** [Volst/prisma-auth#28]
#### I try to create a mutation and get this error. What are you doing wrong?
[This is my source code](https://github.com/gHashTag/auth-prisma-email)

```javascript
mutation {
  signup (
    data: {
      name: "Playra",
      password: "qwertyqwerty",
      email: "raoffonom@icloud.com"
    }
  ) {
    token
  }
}
```

```Error: Variable "$_data" got invalid value {"name":"Playra","email":"raoffonom@icloud.com","password":"$2a$10$ZbnxVxqO7Ya7f7ycpHOC/.hc/aSAga73knEmpEPW47yPpRfnRBwci","emailConfirmToken":"8e6a4be0-30ad-4bb8-afce-6a95b3824edf","emailConfirmed":false,"joinedAt":"2018-06-27T18:31:26.681Z"}; Field "name" is not defined by type UserCreateInput.
Variable "$_data" got invalid value {"name":"Playra","email":"raoffonom@icloud.com","password":"$2a$10$ZbnxVxqO7Ya7f7ycpHOC/.hc/aSAga73knEmpEPW47yPpRfnRBwci","emailConfirmToken":"8e6a4be0-30ad-4bb8-afce-6a95b3824edf","emailConfirmed":false,"joinedAt":"2018-06-27T18:31:26.681Z"}; Field "emailConfirmToken" is not defined by type UserCreateInput.
Variable "$_data" got invalid value {"name":"Playra","email":"raoffonom@icloud.com","password":"$2a$10$ZbnxVxqO7Ya7f7ycpHOC/.hc/aSAga73knEmpEPW47yPpRfnRBwci","emailConfirmToken":"8e6a4be0-30ad-4bb8-afce-6a95b3824edf","emailConfirmed":false,"joinedAt":"2018-06-27T18:31:26.681Z"}; Field "emailConfirmed" is not defined by type UserCreateInput.
Variable "$_data" got invalid value {"name":"Playra","email":"raoffonom@icloud.com","password":"$2a$10$ZbnxVxqO7Ya7f7ycpHOC/.hc/aSAga73knEmpEPW47yPpRfnRBwci","emailConfirmToken":"8e6a4be0-30ad-4bb8-afce-6a95b3824edf","emailConfirmed":false,"joinedAt":"2018-06-27T18:31:26.681Z"}; Field "joinedAt" is not defined by type UserCreateInput.
    at Object.checkResultAndHandleErrors (/Users/xyz/prisma/examples/archive/auth/node_modules/graphql-tools/dist/stitching/errors.js:69:36)
    at Object.<anonymous> (/Users/xyz/prisma/examples/archive/auth/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:92:52)
    at step (/Users/xyz/prisma/examples/archive/auth/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/xyz/prisma/examples/archive/auth/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Users/xyz/prisma/examples/archive/auth/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>```

**Comment by SpaceK33z** [comment]
It looks like you correctly added the `User` model to your `datamodel.graphql`, but didn't deploy those changes in the Prisma service yet. You can do that with `prisma deploy`. After that you should see that your `src/generated/prisma.graphql` has changed.
